// Generated by CoffeeScript 2.5.1
(function() {
  var composition, log, mainprocessmodule, olog, ostr, p, print, recurse;

  mainprocessmodule = {
    name: "mainprocessmodule"
  };

  //region logPrintFunctions
  //#############################################################################
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["mainprocessmodule"] != null) {
      console.log("[mainprocessmodule]: " + arg);
    }
  };

  olog = function(o) {
    return log("\n" + ostr(o));
  };

  ostr = function(o) {
    return JSON.stringify(o, null, 4);
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  //region modulesFromEnvironment
  p = null;

  recurse = null;

  composition = null;

  //endregion

  //###########################################################
  mainprocessmodule.initialize = function() {
    log("mainprocessmodule.initialize");
    p = allModules.pathmodule;
    recurse = allModules.recursemodule;
    composition = allModules.compositionmodule;
  };

  
  //###########################################################
  //region exposedFunctions
  mainprocessmodule.execute = async function(e) {
    log("mainprocessmodule.execute");
    await p.digestPath(e.path);
    if (e.recursive) {
      await recurse.start();
    } else {
      await composition.autocompose(p.root);
    }
  };

  //endregion
  module.exports = mainprocessmodule;

}).call(this);
