// Generated by CoffeeScript 2.5.1
(function() {
  var log, olog, ostr, p, print, recursemodule;

  recursemodule = {
    name: "recursemodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["recursemodule"] != null) {
      console.log("[recursemodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  p = null;

  //###########################################################
  recursemodule.initialize = function() {
    log("recursemodule.initialize");
    p = allModules.pathmodule;
  };

  //###########################################################
  recursemodule.start = function() {
    log("recursemodule.start");
  };

  module.exports = recursemodule;

}).call(this);
